# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET https://localhost:7089/api/foo
Authorization: Bearer CfDJ8JqAJHP6-c5HhHi5O2SQsK3Vs-kh58IgTa5lFWcp4OKYu-hlSuKlTg6YJzD8mQDXvy9Azn8KODfskPm6bFFb-GkxJ5op7aLEwFGgS_17A-wm5SEOvnve-NXVata-tme7yXNEHp2PkICqRzSZkrHCfsQNfwugro2m0bAcso4v1OEvA-3q7Kq0-K8q_ezkESGb3V082JtEoizGIg32-u81Olzwa-xaI7oawIffrV1q2f5_gtCc3y0FZCzIokpsMUrykXLfIQgnmgdc7OczGN7ZRgMxHIGRIz2UUc-iLC4j85td5Eq2ZtHsu_AE9g7KQp47koh2apDPQ1lDh88s-Ih6O1tEVtHxhZQ7ByLEZ7Obpiuur8EkOf3Ezy4O_VJzOiW-lpZ00VjoJ7mIG06dg-5f7BAvZCmfymGo4YwoMfWc8l8XB3FhLiO2NWO893p__tDcpaQTlZ7ZxceUe3ZOQTZz5ojm6jxthwFOTYquOY6SsM-bOSTV0mXLKwEg4GfynLGPaZDYE4BOWVZkAEx0PqBApBoDOhWAnQ_4Ey2XV7X3OdHY2ZDXbVwkYwHKGvCES_6KcMGhyjLjfEPimk4S-fgcd6KRik-RC8Lt_yKD4PBBe_GFFJDGzcn54oZ93sCqobljrW60lM5OPyiPPqypACcy32GzPL2AXAKX5M0LJSTycNDjyHQzNwAhz_a6eTuIC65pBg

###

POST https://localhost:7089/api/auth/login
Content-Type: application/json

{
  "email": "authen@gmail.com",
  "password": "@Authen123" 
}