import { Room } from "./Dorm";

export const room: Room[] = [
  {
    id: "1",
    name: "Room A",
    status: "Available",
    description: "A nice room",
    houseName: "House 1",
    roomType: "Single",
    price: "100",
    floorName: "First",
    dormName: "Dorm 1",
    Capacity: 10,
  },
  {
    id: "2",
    name: "Room B",
    status: "Occupied",
    description: "A spacious room",
    houseName: "House 2",
    roomType: "Double",
    price: "200",
    floorName: "Second",
    dormName: "Dorm 2",
    Capacity: 10,
  },
  {
    id: "3",
    name: "Room C",
    status: "Available",
    description: "A cozy room",
    houseName: "House 3",
    roomType: "Single",
    price: "150",
    floorName: "Third",
    dormName: "Dorm 3",
    Capacity: 10,
  },
  {
    id: "4",
    name: "Room D",
    status: "Occupied",
    description: "A comfortable room",
    houseName: "House 4",
    roomType: "Double",
    price: "250",
    floorName: "Fourth",
    dormName: "Dorm 4",
    Capacity: 10,
  },
  {
    id: "5",
    name: "Room E",
    status: "Available",
    description: "A modern room",
    houseName: "House 5",
    roomType: "Single",
    price: "120",
    floorName: "First",
    dormName: "Dorm 1",
    Capacity: 10,
  },
  {
    id: "6",
    name: "Room F",
    status: "Occupied",
    description: "A spacious room",
    houseName: "House 6",
    roomType: "Double",
    price: "220",
    floorName: "Second",
    dormName: "Dorm 2",
    Capacity: 10,
  },
  {
    id: "7",
    name: "Room G",
    status: "Available",
    description: "A cozy room",
    houseName: "House 7",
    roomType: "Single",
    price: "170",
    floorName: "Third",
    dormName: "Dorm 3",
    Capacity: 10,
  },
  {
    id: "8",
    name: "Room H",
    status: "Occupied",
    description: "A comfortable room",
    houseName: "House 8",
    roomType: "Double",
    price: "270",
    floorName: "Fourth",
    dormName: "Dorm 4",
    Capacity: 10,
  },
  {
    id: "9",
    name: "Room I",
    status: "Available",
    description: "A modern room",
    houseName: "House 9",
    roomType: "Single",
    price: "130",
    floorName: "First",
    dormName: "Dorm 1",
    Capacity: 10,
  },
  {
    id: "10",
    name: "Room J",
    status: "Occupied",
    description: "A spacious room",
    houseName: "House 10",
    roomType: "Double",
    price: "230",
    floorName: "Second",
    dormName: "Dorm 2",
    Capacity: 10,
  },
  {
    id: "11",
    name: "Room K",
    status: "Available",
    description: "A cozy room",
    houseName: "House 11",
    roomType: "Single",
    price: "180",
    floorName: "Third",
    dormName: "Dorm 3",
    Capacity: 10,
  },
  {
    id: "12",
    name: "Room L",
    status: "Occupied",
    description: "A comfortable room",
    houseName: "House 12",
    roomType: "Double",
    price: "280",
    floorName: "Fourth",
    dormName: "Dorm 4",
    Capacity: 10,
  },
  {
    id: "13",
    name: "Room M",
    status: "Available",
    description: "A modern room",
    houseName: "House 13",
    roomType: "Single",
    price: "140",
    floorName: "First",
    dormName: "Dorm 1",
    Capacity: 10,
  },
  {
    id: "14",
    name: "Room N",
    status: "Occupied",
    description: "A spacious room",
    houseName: "House 14",
    roomType: "Double",
    price: "240",
    floorName: "Second",
    dormName: "Dorm 2",
    Capacity: 10,
  },
  {
    id: "15",
    name: "Room O",
    status: "Available",
    description: "A cozy room",
    houseName: "House 15",
    roomType: "Single",
    price: "190",
    floorName: "Third",
    dormName: "Dorm 3",
    Capacity: 10,
  },
  {
    id: "16",
    name: "Room P",
    status: "Occupied",
    description: "A comfortable room",
    houseName: "House 16",
    roomType: "Double",
    price: "290",
    floorName: "Fourth",
    dormName: "Dorm 4",
    Capacity: 10,
  },
  {
    id: "17",
    name: "Room Q",
    status: "Available",
    description: "A modern room",
    houseName: "House 17",
    roomType: "Single",
    price: "150",
    floorName: "First",
    dormName: "Dorm 1",
    Capacity: 10,
  },
  {
    id: "18",
    name: "Room R",
    status: "Occupied",
    description: "A spacious room",
    houseName: "House 18",
    roomType: "Double",
    price: "250",
    floorName: "Second",
    dormName: "Dorm 2",
    Capacity: 10,
  },
  {
    id: "19",
    name: "Room S",
    status: "Available",
    description: "A cozy room",
    houseName: "House 19",
    roomType: "Single",
    price: "160",
    floorName: "Third",
    dormName: "Dorm 3",
    Capacity: 10,
  },
  {
    id: "20",
    name: "Room T",
    status: "Occupied",
    description: "A comfortable room",
    houseName: "House 20",
    roomType: "Double",
    price: "300",
    floorName: "Fourth",
    dormName: "Dorm 4",
    Capacity: 10,
  },
];
